os: linux
install:
- brew install docker docker-machine
- docker-machine create --driver virtualbox default
- eval $(docker-machine env default)
- docker pull swiftdocker/swift
script:
- docker run -it -v `pwd`:/project swiftdocker/swift bash
- cd /project
- swift build & swift test
