os: linux
sudo: required
dist: trusty
before_install:
  - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
  - wget https://swift.org/builds/swift-3.0-preview-6/ubuntu1404/swift-3.0-PREVIEW-6/swift-3.0-PREVIEW-6-ubuntu14.04.tar.gz
  - tar xzf swift-3.0-PREVIEW-6-ubuntu14.04.tar.gz
  - export PATH=${PWD}/swift-3.0-PREVIEW-6-ubuntu14.04.tar.gz/usr/bin:"${PATH}"
script:
  - git clone https://github.com/apple/swift-package-manager
  - cd swift-package-manager && cd ../
  - swift-package-manager/Utilities/bootstrap
  - ${PWD}/swift-package-manager/.build/debug/swift-build
  - ${PWD}/swift-package-manager/.build/debug/swift-test
