matrix:
  fast-finish: true
  include:
    - os: osx
      language: swift
      osx_image: xcode8
    - os: linux
      sudo: required
      dist: trusty

notifications:
  slack: pauljohanneskraft:uXzmppJPaAEt8adnz6AbsHSf

before_install:
- if [[ $TRAVIS_OS_NAME == linux ]]; then 
      sh linux-swift-install.sh;
  fi
  
- if [[ $TRAVIS_OS_NAME == osx   ]]; then 
      gem install xcpretty-travis-formatter; 
  fi

install:
- if [[ $TRAVIS_OS_NAME == linux ]]; then 
      sh linux.sh;
  fi

script:
- if [[ $TRAVIS_OS_NAME == linux ]]; then 
      swift test && echo "Tests passed."; 
      swift package --version && 
      swift build;
  fi
  
- if [[ $TRAVIS_OS_NAME == osx   ]]; then 
      xcodebuild -workspace Math.xcworkspace -scheme MathTests test | xcpretty -f `xcpretty-travis-formatter` && 
      export status=${PIPESTATUS[0]} &&
      bash <(curl -s https://codecov.io/bash) && 
      exit ${status}; 
  fi
