branches:
  only:
  - master
  - Development
  - Feature

matrix:
  allow_failures:
    - os: linux
      language: objective-c
      dist: trusty
      sudo: required
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8

before_install:
- if [[ $TRAVIS_OS_NAME == linux ]]; then wget https://swift.org/builds/swift-3.0-preview-6/ubuntu1404/swift-3.0-PREVIEW-6/swift-3.0-PREVIEW-6-ubuntu14.04.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then tar xzf swift-3.0-PREVIEW-6-ubuntu14.04.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then export PATH=${PWD}/swift-3.0-PREVIEW-6-ubuntu14.04/usr/bin:"${PATH}"; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then wget https://github.com/apple/swift-package-manager/archive/swift-DEVELOPMENT-SNAPSHOT-2016-08-25-a.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then tar xzf swift-DEVELOPMENT-SNAPSHOT-2016-08-25-a.tar.gz; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then export PATH=${PWD}/swift-DEVELOPMENT-SNAPSHOT-2016-08-25-a/usr/bin:"${PATH}"; fi
- if [[ $TRAVIS_OS_NAME == osx   ]]; then gem install xcpretty-travis-formatter; fi
script:
- if [[ $TRAVIS_OS_NAME == linux ]]; then swift package --version; fi
- if [[ $TRAVIS_OS_NAME == linux ]]; then swift build; fi
- if [[ $TRAVIS_OS_NAME == osx   ]]; then xcodebuild test -workspace Math.xcworkspace -scheme Math | xcpretty -f `xcpretty-travis-formatter` && exit ${PIPESTATUS[0]}; fi
